### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by ralexay** [GuyKh/iec-custom-component#103]
### System Health details

Error doing job: Task exception was never retrieved

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: homeassistant
Source: custom_components/iec/coordinator.py:413
integration: Israel Electric Corporation (IEC) ([documentation](https://github.com/guykh/iec-custom-component), [issues](https://github.com/guykh/iec-custom-component/issues))
First occurred: April 25, 2024 at 19:08:33 (7 occurrences)
Last logged: 01:09:53

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/iec/coordinator.py", line 413, in _insert_statistics
    if key <= TIMEZONE.localize(last_stat_req_hour):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytz/tzinfo.py", line 321, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)

### Reproduction steps

Just wait till refresh

### Debug logs

```text
2024-04-25 22:37:19.812 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/iec/coordinator.py", line 413, in _insert_statistics
if key <= TIMEZONE.localize(last_stat_req_hour):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pytz/tzinfo.py", line 321, in localize
raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
2024-04-25 22:37:20.802 DEBUG (MainThread) [iec_api.commons] HTTP POST Response: {'status': 0, 'futureConsumptionInfo': {'lastInvoiceDate': None, 'currentDate': '2024-04-25', 'futureConsumption': 6.346, 'totalImport': 6839.079, 'totalImportDate': '2024-04-25'}, 'fromDate': '2024-04-25', 'toDate': '2024-04-25', 'totalConsumptionForPeriod': 6.346, 'totalImportDateForPeriod': '2024-04-25', 'meterStartDate': '2023-10-24', 'totalImport': 6839.079, 'data': [{'status': 0, 'date': '2024-04-25T00:00:00.000000', 'value': 0.423}, {'status': 0, 'date': '2024-04-25T00:15:00.000000', 'value': 0.487}, {'status': 0, 'date': '2024-04-25T00:30:00.000000', 'value': 0.44}, {'status': 0, 'date': '2024-04-25T00:45:00.000000', 'value': 0.238}, {'status': 0, 'date': '2024-04-25T01:00:00.000000', 'value': 0.322}, {'status': 0, 'date': '2024-04-25T01:15:00.000000', 'value': 0.345}, {'status': 0, 'date': '2024-04-25T01:30:00.000000', 'value': 0.329}, {'status': 0, 'date': '2024-04-25T01:45:00.000000', 'value': 0.318}, {'status': 0, 'date': '2024-04-25T02:00:00.000000', 'value': 0.284}, {'status': 0, 'date': '2024-04-25T02:15:00.000000', 'value': 0.267}, {'status': 0, 'date': '2024-04-25T02:30:00.000000', 'value': 0.265}, {'status': 0, 'date': '2024-04-25T02:45:00.000000', 'value': 0.288}, {'status': 0, 'date': '2024-04-25T03:00:00.000000', 'value': 0.272}, {'status': 0, 'date': '2024-04-25T03:15:00.000000', 'value': 0.262}, {'status': 0, 'date': '2024-04-25T03:30:00.000000', 'value': 0.303}, {'status': 0, 'date': '2024-04-25T03:45:00.000000', 'value': 0.242}, {'status': 0, 'date': '2024-04-25T04:00:00.000000', 'value': 0.241}, {'status': 0, 'date': '2024-04-25T04:15:00.000000', 'value': 0.278}, {'status': 0, 'date': '2024-04-25T04:30:00.000000', 'value': 0.234}, {'status': 0, 'date': '2024-04-25T04:45:00.000000', 'value': 0.251}, {'status': 0, 'date': '2024-04-25T05:00:00.000000', 'value': 0.257}]}
```

Formatted JSON
```json
{
  "status": 0,
  "futureConsumptionInfo": {
    "lastInvoiceDate": None,
    "currentDate": "2024-04-25",
    "futureConsumption": 6.346,
    "totalImport": 6839.079,
    "totalImportDate": "2024-04-25"
  },
  "fromDate": "2024-04-25",
  "toDate": "2024-04-25",
  "totalConsumptionForPeriod": 6.346,
  "totalImportDateForPeriod": "2024-04-25",
  "meterStartDate": "2023-10-24",
  "totalImport": 6839.079,
  "data": [{
    "status": 0,
    "date": "2024-04-25T00:00:00.000000",
    "value": 0.423
  }, {
    "status": 0,
    "date": "2024-04-25T00:15:00.000000",
    "value": 0.487
  }, {
    "status": 0,
    "date": "2024-04-25T00:30:00.000000",
    "value": 0.44
  }, {
    "status": 0,
    "date": "2024-04-25T00:45:00.000000",
    "value": 0.238
  }, {
    "status": 0,
    "date": "2024-04-25T01:00:00.000000",
    "value": 0.322
  }, {
    "status": 0,
    "date": "2024-04-25T01:15:00.000000",
    "value": 0.345
  }, {
    "status": 0,
    "date": "2024-04-25T01:30:00.000000",
    "value": 0.329
  }, {
    "status": 0,
    "date": "2024-04-25T01:45:00.000000",
    "value": 0.318
  }, {
    "status": 0,
    "date": "2024-04-25T02:00:00.000000",
    "value": 0.284
  }, {
    "status": 0,
    "date": "2024-04-25T02:15:00.000000",
    "value": 0.267
  }, {
    "status": 0,
    "date": "2024-04-25T02:30:00.000000",
    "value": 0.265
  }, {
    "status": 0,
    "date": "2024-04-25T02:45:00.000000",
    "value": 0.288
  }, {
    "status": 0,
    "date": "2024-04-25T03:00:00.000000",
    "value": 0.272
  }, {
    "status": 0,
    "date": "2024-04-25T03:15:00.000000",
    "value": 0.262
  }, {
    "status": 0,
    "date": "2024-04-25T03:30:00.000000",
    "value": 0.303
  }, {
    "status": 0,
    "date": "2024-04-25T03:45:00.000000",
    "value": 0.242
  }, {
    "status": 0,
    "date": "2024-04-25T04:00:00.000000",
    "value": 0.241
  }, {
    "status": 0,
    "date": "2024-04-25T04:15:00.000000",
    "value": 0.278
  }, {
    "status": 0,
    "date": "2024-04-25T04:30:00.000000",
    "value": 0.234
  }, {
    "status": 0,
    "date": "2024-04-25T04:45:00.000000",
    "value": 0.251
  }, {
    "status": 0,
    "date": "2024-04-25T05:00:00.000000",
    "value": 0.257
  }]
}
```

**Comment by GuyKh** [comment]
@ralexay merged a fix, please take a look at the next release (soon...)

**Comment by ralexay** [comment]
seems to work fine now, thanks
