### ISSUE TITLE
Fetching data on the first of the month fails with an exception

### ISSUE THREAD

**Issue by mikeage** [GuyKh/iec-custom-component#107]
### System Health details

sorry, can't be bothered now :-)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Running the integration this morning gave this error:

```
2024-05-01 09:46:39.156 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: unhashable type: 'RemoteReading'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 252, in _async_update_data
    list(dict.fromkeys(daily_readings[device.device_number])))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'RemoteReading'
```

I worked around it by monkeypatching the RemoteReading class directly in the coordinator.py file, right before this line:
```python
RemoteReading.__hash__ = lambda self: hash((self.status, self.date, self.value))
```

But the proper fix is to add a `__hash__` function to https://github.com/GuyKh/py-iec-api/blob/main/iec_api/models/remote_reading.py#L72 . I think my implementation (`hash((self.status, self.date, self.value))`) should be sufficient.

### Reproduction steps

1. Wait until the first day of the month
2. Expect data to be fetched
...

### Debug logs

```text
See above
```

**Comment by mikeage** [comment]
Because I run HA in a container, it was a bit more trouble to actually patch the underlying py-iec-api, which is why I didn't do it that way. I opened the issue here because anyone else who sees this is likely to start at this repo, not at py-iec-api

**Comment by GuyKh** [comment]
Thanks @mikeage. I'll add a fix to `py-iec-api` and will add it here :)

**Comment by GuyKh** [comment]
@mikeage - I'd appreciate if you'll code-review the [fix PR](https://github.com/GuyKh/py-iec-api/pull/106)

**Comment by GuyKh** [comment]
Keeping it open for verification

**Comment by GuyKh** [comment]
Should be fixed in 0.0.26 - @mikeage please verify

**Comment by GuyKh** [comment]
Thanks @mikeage
