### ISSUE TITLE
Unexpected error fetching Iec data

### ISSUE THREAD

**Issue by moryoav** [GuyKh/iec-custom-component#145]
## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4810
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 116.7 GB
disk_used | 79.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), eufy-security-ws (1.8.0-2), Home Assistant Google Drive Backup (0.112.1), File editor (5.8.0), ArgonOne Active Linear Cooling (30a), Node-RED (18.0.4), Mosquitto broker (6.4.1), Whatsapp (1.4.0), Samba share (12.3.2), ESPHome (2024.7.3), Unraid API-RE (2.0), VLC (0.3.0), Anylist (1.7.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 24
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 4, 2024 at 20:41
-- | --
current_recorder_run | August 12, 2024 at 08:53
estimated_db_size | 1195.43 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 5 / 6
local_online | 4 / 4

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration worked properly up till recently. Perhaps the issue is related to the latest Home Assistant update (2024.8).
The integration now doesn't load, it says "Failed setup, will retry:'NoneType' object is not subscriptable.
In the logs I see it correctly fetches meter readings properly
With a lot of lines that look like this:
{"status":0,"date":"2024-08-10T23:30:00.000000","value":0.629},{"status":0,"date":"2024-08-10T23:45:00.000000","value":0.623}

So it appears to be properly connecting and fetching data.

However at the end of the logs I then get:
```
2024-08-12 09:16:08.383 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.384 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.384 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.385 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.385 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.385 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.386 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.386 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.387 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.387 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.388 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.388 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.388 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.389 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.390 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.390 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.390 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.391 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.391 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.391 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-12 09:16:08.392 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/iec/coordinator.py", line 377, in _async_update_data
last_meter_read = int(devices_by_id.counter_devices[0].last_mr)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-08-12 09:16:08.395 DEBUG (MainThread) [custom_components.iec.coordinator] Finished fetching Iec data in 8.977 seconds (success: False)
```

### Reproduction steps

1. Install the integration.
2. Observe.

### Debug logs

```text
Too much private information in the debug logs, I'll provide privately if needed.
```

**Comment by moryoav** [comment]
Fixed in version 0.0.30
