### ISSUE TITLE
Failed setup, will retry: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by maorcc** [GuyKh/iec-custom-component#148]
### System Health details

system is healthy

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration worked fine until 4 days ago.
For some reason, it stopped and got into a re-setup loop where it keeps doing setup and failing.

![image](https://github.com/user-attachments/assets/867fd9f1-962e-483c-9356-3082b6a3e633)

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
2024-08-15 14:24:47.276 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.278 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.278 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.278 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"counterDevices":null,"mrType":"00"},"reponseDescriptor":{"isSuccess":false,"code":"07","description":"No authorization for this type of product: Private Producer"}}
2024-08-15 14:24:47.279 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 377, in _async_update_data
    last_meter_read = int(devices_by_id.counter_devices[0].last_mr)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-08-15 14:24:47.282 DEBUG (MainThread) [custom_components.iec.coordinator] Finished fetching Iec data in 13.334 seconds (success: False)






Before that, I see in the log a lot of messages like these (changed private numbers):

2024-08-15 14:24:46.036 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.036 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.036 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.036 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.037 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.037 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.037 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.038 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.038 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.038 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.038 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.038 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.039 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.040 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.041 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.041 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.041 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
2024-08-15 14:24:46.041 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/Device/888888888888/8888888
```

**Comment by GuyKh** [comment]
@maorcc have you just changed your meter recently?
Have you upgraded the `iec` addon recently?

**Comment by GuyKh** [comment]
I see you're using version 0.0.28
Try upgrading to 0.0.30 (or 0.0.31-beta)?

**Comment by maorcc** [comment]
Yes. The upgrade has resolved the issue.  Thanks!
