### ISSUE TITLE
Unable to start due to TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by enudler** [GuyKh/iec-custom-component#189]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4981
Installed Version | 2.0.1
Stage | running
Available Repositories | 1512
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 10, 2024 at 4:46 PM
-- | --
current_recorder_run | October 18, 2024 at 10:46 AM
estimated_db_size | 59.76 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Plugin unable to start due to TypeError: 'NoneType' object is not subscriptable
The plugin used to work find until a month or two ago,
I tried version 0.34 and version 0.36 beta 3

### Reproduction steps

1. Install the plugin
2. Enable it and submit the otp
3. Error will raise 

### Debug logs

```text
2024-10-18 07:57:06.172 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"contractAccount":"xxxxxxxxx","lastMeters":[{"meterReadings":[{"reading":9294,"readingCode":"25","readingDate":"2024-09-11T00:00:00","usage":"3287","serialNumber":null},{"reading":6007,"readingCode":"25","readingDate":"2024-07-11T00:00:00","usage":"2315","serialNumber":null},{"reading":3692,"readingCode":"25","readingDate":"2024-05-15T00:00:00","usage":"1034","serialNumber":null},{"reading":2658,"readingCode":"25","readingDate":"2024-03-31T00:00:00","usage":"470","serialNumber":null},{"reading":2188,"readingCode":"25","readingDate":"2024-03-13T00:00:00","usage":"1262","serialNumber":null}],"serialNumber":"000000000022004308","materialNumber":"000000000000000509","registerNumber":"000000000000000001"}]},"reponseDescriptor":{"isSuccess":true,"code":"00","description":""}}
2024-10-18 07:57:06.172 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"contractAccount":"348249229","lastMeters":[{"meterReadings":[{"reading":9294,"readingCode":"25","readingDate":"2024-09-11T00:00:00","usage":"3287","serialNumber":null},{"reading":6007,"readingCode":"25","readingDate":"2024-07-11T00:00:00","usage":"2315","serialNumber":null},{"reading":3692,"readingCode":"25","readingDate":"2024-05-15T00:00:00","usage":"1034","serialNumber":null},{"reading":2658,"readingCode":"25","readingDate":"2024-03-31T00:00:00","usage":"470","serialNumber":null},{"reading":2188,"readingCode":"25","readingDate":"2024-03-13T00:00:00","usage":"1262","serialNumber":null}],"serialNumber":"000000000022004308","materialNumber":"000000000000000509","registerNumber":"000000000000000001"}]},"reponseDescriptor":{"isSuccess":true,"code":"00","description":""}}
2024-10-18 07:57:06.173 DEBUG (MainThread) [custom_components.iec.coordinator] Last Reading for contract 348249229, Meter 22004308: MeterReading(reading=9294, reading_code='25', reading_date=datetime.datetime(2024, 9, 11, 0, 0, tzinfo=<DstTzInfo 'Asia/Jerusalem' IDT+3:00:00 DST>), usage='3287', serial_number=None)
2024-10-18 07:57:06.173 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.173 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.173 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.173 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.174 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.174 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.174 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.174 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.174 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/outages/accounts
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":null,"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-10-18 07:57:06.277 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 423, in _async_update_data
    total_kva_price, estimated_kwh_consumption = await self._estimate_bill(contract_id, device.device_number,
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 658, in _estimate_bill
    account_id = await self._get_account_id()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 177, in _get_account_id
    account = await self.api.get_default_account()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 126, in get_default_account
    return accounts[0]
           ~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-10-18 07:57:06.279 DEBUG (MainThread) [custom_components.iec.coordinator] Finished fetching Iec data in 11.570 seconds (success: False)
```

**Comment by GuyKh** [comment]
@enudler can you double check that these credentials work with IEC site?

**Comment by enudler** [comment]
Hi
Yes, they are working

**Comment by GuyKh** [comment]
So, the issue here is that the accounts API returns `null` as data, rather than standard reply.
This is super odd.

I'm adding a code that would "handle" or "swallow" this error - which will avoid calculating estimated_bill

**Comment by enudler** [comment]
Thanks @GuyKh 
I will test it once it's ready

**Comment by GuyKh** [comment]
Try with `0.0.36`

**Comment by enudler** [comment]
<img width="479" alt="iec" src="https://github.com/user-attachments/assets/e0bdf46b-a882-443f-96d3-8dc690cc205f">
Getting above error after OTP insert
tested in 0.36 and 0.34 - both giving same error
OTP Works fine on IEC website.

maybe they changed the api?

**Comment by GuyKh** [comment]
It's still very odd that the response from "getAccounts" is `null`.
