### ISSUE TITLE
After upgrading to 0.0.39, there are errors in the logs : mashumaro.exceptions.InvalidFieldValue

### ISSUE THREAD

**Issue by sefininio** [GuyKh/iec-custom-component#206]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 4.15.0-194-generic
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1471
Downloaded Repositories | 22

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 17, 2025 at 3:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
instance_id | a4de4ad502b54059a52696a01502c0d2
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 10
views | 42
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 1, 2024 at 5:32 AM
-- | --
current_recorder_run | November 6, 2024 at 8:51 AM
estimated_db_size | 1807.80 MiB
database_engine | mysql
database_version | 11.5.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After updating to 0.0.39, getting errors in the logs

### Reproduction steps

1. Update to 0.0.39
2. Check the logs
3.
...

### Debug logs

```text
--- Logging error ---
2024-11-06 09:57:35.872 WARNING (MainThread) [iec_api.commons] Failed call: (Code 204): No Content
Traceback (most recent call last):
  File "/config/custom_components/iec/coordinator.py", line 189, in _get_kva_tariff
    self._kva_tariff = await self.api.get_kva_tariff()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 511, in get_kva_tariff
    return await static_data.get_kva_tariff(self._session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/static_data.py", line 93, in get_kva_tariff
    await _get_tariffs(session)
  File "/usr/local/lib/python3.12/site-packages/iec_api/static_data.py", line 42, in _get_tariffs
    response = await commons.send_get_request(session=session, url=GET_KWH_TARIFF_URL)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/commons.py", line 125, in send_get_request
    parse_error_response(resp, json_resp)
  File "/usr/local/lib/python3.12/site-packages/iec_api/commons.py", line 102, in parse_error_response
    raise IECError(resp.status, resp.reason)
iec_api.models.exceptions.IECError: (Code 204): No Content
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/logging/handlers.py", line 1493, in emit
    self.enqueue(self.prepare(record))
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/handlers.py", line 1475, in prepare
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/iec/__init__.py", line 21, in async_setup_entry
    await iec_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/iec/coordinator.py", line 389, in _async_update_data
    kva_tariff = await self._get_kva_tariff()
  File "/config/custom_components/iec/coordinator.py", line 191, in _get_kva_tariff
    _LOGGER.exception("Failed fetching KVA Tariff", e)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1574, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 41, in handle
    self.emit(record)
Message: 'Failed fetching KVA Tariff'
Arguments: (IECError('(Code 204): No Content'),)
2024-11-06 09:57:39.567 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data
Traceback (most recent call last):
  File "<string>", line 124, in __mashumaro_from_dict__
  File "<string>", line 12, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "reading_code" of type str is missing in MeterReading instance
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 14, in __mashumaro_from_dict__
  File "<string>", line 126, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "meter_readings" of type list[MeterReading] in Invoice has invalid value [{'reading': 184072.0, 'readingDate': '0001-01-01T00:00:00', 'serialNumber': '<<< manual redacted log value>>>'}]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
  File "<string>", line 16, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "invoices" of type list[Invoice] in GetInvoicesBody has invalid value 
<<< manual redacted log value - contact to receive it privately >>>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 413, in _async_update_data
    billing_invoices = await self.api.get_billing_invoices(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 471, in get_billing_invoices
    return await data.get_billing_invoices(self._session, self._token, bp_number, contract_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 272, in get_billing_invoices
    return await _get_response_with_descriptor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 79, in _get_response_with_descriptor
    response_with_descriptor = decoder.decode(response)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 10, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
mashumaro.exceptions.InvalidFieldValue: Field "data" of type Optional[GetInvoicesBody] in ResponseWithDescriptor has invalid value {'property': {'areaId': '0802', 'districtId': 8}, 'invoices': <<< manual redacted log value - contact to receive it privately >>> }
2024-11-06 09:57:39.972 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "<string>", line 15, in __mashumaro_from_dict__
  File "<string>", line 6, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "last_invoice_date" of type Optional[str] is missing in FutureConsumptionInfo instance
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/iec/coordinator.py", line 691, in _insert_statistics
    readings = await self._get_readings(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 274, in _get_readings
    reading = await self.api.get_remote_reading(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 410, in get_remote_reading
    return await data.get_remote_reading(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 157, in get_remote_reading
    return RemoteReadingResponse.from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "future_consumption_info" of type FutureConsumptionInfo in RemoteReadingResponse has invalid value {'currentDate': '2024-11-05', 'futureConsumption': 31.424, 'totalImport': 11653.433, 'totalImportDate': '2024-11-06'}
```

**Comment by GuyKh** [comment]
There are two issues with the logs you're sharing:
1. calling `get_kva_tariff()` returns (Code 204): No Content -- this was the fix that lead to 0.0.39 - with bad parsing before.
2. `Field "future_consumption_info" of type FutureConsumptionInfo in RemoteReadingResponse has invalid value {'currentDate': '2024-11-05', 'futureConsumption': x424, 'totalImport': x433, 'totalImportDate': '2024-11-06'}`

I'll look into this

**Comment by sefininio** [comment]
0.0.40 download fails...?

```
2024-11-06 11:18:27.149 ERROR (MainThread) [custom_components.hacs] <Integration GuyKh/iec-custom-component> Failed to download [https://github.com/GuyKh/iec-custom-component/releases/download/tags/0.0.40/iec.zip](https://github.com/GuyKh/iec-custom-component/releases/download/tags/0.0.40/iec.zip%3C/span%3E)
2024-11-06 11:18:27.156 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139828448131632] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 1436, in async_download_repository
    await self.async_install(version=ref)
  File "/config/custom_components/hacs/repositories/base.py", line 884, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 986, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1438, in async_download_repository
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Downloading GuyKh/iec-custom-component with version 0.0.40 failed with (Could not download, see log for details)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 463, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: Downloading GuyKh/iec-custom-component with version 0.0.40 failed with (Could not download, see log for details)
```

**Comment by tzagim** [comment]
@GuyKh 
You need to regenerate the tag.
According to my experience, a retry is on the same workflow content that was at the time of creation, that's how it is in GitHub......

**Comment by GuyKh** [comment]
Try with 0.0.40

**Comment by tzagim** [comment]
@GuyKh 
```
ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing component custom_components.iec
File "/config/custom_components/iec/__init__.py", line 10, in <module>
File "/config/custom_components/iec/const.py", line 5, in <module>
from iec_api.models.invoice import Invoice
File "/usr/local/lib/python3.12/site-packages/iec_api/models/invoice.py", line 60, in <module>
ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.iec
File "/config/custom_components/iec/__init__.py", line 10, in <module>
File "/config/custom_components/iec/const.py", line 5, in <module>
from iec_api.models.invoice import Invoice
File "/usr/local/lib/python3.12/site-packages/iec_api/models/invoice.py", line 60, in <module>
ImportError: Exception importing custom_components.iec
File "/config/custom_components/iec/__init__.py", line 10, in <module>
File "/config/custom_components/iec/const.py", line 5, in <module>
from iec_api.models.invoice import Invoice
File "/usr/local/lib/python3.12/site-packages/iec_api/models/invoice.py", line 60, in <module>
ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'iec': Unable to import component: Exception importing custom_components.iec
File "/config/custom_components/iec/__init__.py", line 10, in <module>
File "/config/custom_components/iec/const.py", line 5, in <module>
from iec_api.models.invoice import Invoice
File "/usr/local/lib/python3.12/site-packages/iec_api/models/invoice.py", line 60, in <module>
ImportError: Exception importing custom_components.iec
File "/config/custom_components/iec/__init__.py", line 10, in <module>
File "/config/custom_components/iec/const.py", line 5, in <module>
from iec_api.models.invoice import Invoice
File "/usr/local/lib/python3.12/site-packages/iec_api/models/invoice.py", line 60, in <module>
ImportError: Exception importing custom_components.iec
```

**Comment by GuyKh** [comment]
Looking

**Comment by GuyKh** [comment]
try with 0.0.40.1

**Comment by tzagim** [comment]
> try with 0.0.40.1

No iec.zip

**Comment by GuyKh** [comment]
Try with 0.0.40.2

**Comment by tzagim** [comment]
> Try with 0.0.40.2

```
ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data
Traceback (most recent call last):
File "<string>", line 84, in __mashumaro_from_dict__
File "<string>", line 12, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "reading_code" of type str is missing in MeterReading instance
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 14, in __mashumaro_from_dict__
File "<string>", line 86, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "meter_readings" of type list[MeterReading] in Invoice has invalid value [{'reading': 98745.0, 'readingDate': '0001-01-01T00:00:00', 'serialNumber': '0000000000987654'}]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 8, in __mashumaro_from_dict_........
File "<string>", line 16, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "invoices" of type list[Invoice] in GetInvoicesBody has invalid value [{'consumption' ........ 'hasDirectDebit': True, 'invoiceType': 0}]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/iec/coordinator.py", line 413, in _async_update_data
billing_invoices = await self.api.get_billing_invoices(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 470, in get_billing_invoices
return await data.get_billing_invoices(self._session, self._token, bp_number, contract_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 272, in get_billing_invoices
return await _get_response_with_descriptor(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 79, in _get_response_with_descriptor
response_with_descriptor = decoder.decode(response)
^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 10, in __mashumaro_from_dict_......
mashumaro.exceptions.InvalidFieldValue: Field "data" of type Optional[GetInvoicesBody] in ResponseWithDescriptor has invalid value {'property': .........
```

**Comment by tzagim** [comment]
#212 
duplication

**Comment by GuyKh** [comment]
@sefininio - when you set `iec_api` as debug ->
```
logs:
logger:
  default: info
  logs:
    iec_api: debug
```

You'll be able to see the HTTP Calls (POST/GET).
Could you change it, restart HA - and share the **content** of response with `MeterReadings` json field

**Comment by sefininio** [comment]
> @sefininio - can you set `iec_api` as debug ->
> 
> ```
> logs:
> logger:
>   default: info
>   logs:
>     iec_api: debug
> ```
> 
> You'll be able to see the HTTP Calls (POST/GET). Could you change it, restart HA - and share the **content** of response with `MeterReadings` json field

Sure. But how can I share it with you privately? I dont want to post the full private data here in plain text

**Comment by sefininio** [comment]
@GuyKh 
OK, I shared it in a secure pastebin: https://defuse.ca/b/85m59HE6
The password is my phone number - you know it :)

Let me know if that doesnt work.

**Comment by GuyKh** [comment]
@sefininio - fixed. Try again with 0.0.40.4
If something is broken again - same story - logs please

**Comment by sefininio** [comment]
@GuyKh 
Something broke - not sure what... 
After upgrade got some errors in the logs and entities became unavailable. I though I need to remove and config again like in previous versions - now can't config the extension.
Logs: https://defuse.ca/b/4oUvGczr - same password.

**Comment by GuyKh** [comment]
@sefininio - tried with your details and it indeed loads successfully.

The 403 error is originated in IEC API

**Comment by sefininio** [comment]
Yup, probably some iec api timeouts or instabilty. Tried a few hours later and it worked :)
