### ISSUE TITLE
IEC integration failure

### ISSUE THREAD

**Issue by hros** [GuyKh/iec-custom-component#233]
### System Health details

Core - 2024.11.3
Frontend - 20241106.2
IEC - 0.0.43

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

IEC data not available
integration used to work but stopped working
removing the integration and reinstalling it didn't fix the issue (successfully received the IEC OTP)

the integration used to display entities automatically but does not display any entities now
the attached debug log (with redacted personal info) shows several errors (at the end of the log)

### Reproduction steps

1. update IEC integration to the latest version
2. add integration
4. enter ID and OTP
5. enable log

### Debug logs

```text
2024-12-05 19:28:15.883 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration iec which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-05 19:28:27.874 INFO (SyncWorker_8) [homeassistant.util.package] Attempting install of iec-api==0.4.10
2024-12-05 19:28:40.296 INFO (MainThread) [homeassistant.setup] Setting up iec
2024-12-05 19:28:40.296 INFO (MainThread) [homeassistant.setup] Setup of domain iec took 0.00 seconds
2024-12-05 19:28:40.296 DEBUG (MainThread) [custom_components.iec.coordinator] Initializing IEC Coordinator
2024-12-05 19:28:40.298 DEBUG (MainThread) [custom_components.iec.coordinator] Loading API token from config entry
2024-12-05 19:28:40.298 DEBUG (MainThread) [custom_components.iec.coordinator] Checking if API token needs to be refreshed
2024-12-05 19:28:40.299 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/customer/contract/xxxxxxxxx
2024-12-05 19:28:43.217 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"data":{"contracts":[{"address":"my address","contractId":"my contract","dueDate":"1900-01-01","totalDebt":0.0,"frequency":2,"status":1,"fromPativteProducer":true,"cityCode":"city code","cityName":"city name","streetCode":"street code","streetName":"street name","houseNumber":"xx","debtForInvoicesDueDateNotPassed":0.0,"isTouz":false,"smartMeter":true,"producerType":1,"isDomestic":true},{"address":"2nd address - previous contract","contractId":"contract2","dueDate":"1900-01-01","totalDebt":0.0,"frequency":2,"status":2,"fromPativteProducer":false,"cityCode":"xxxxx","cityName":"city name","streetCode":"xxx","streetName":"street name","houseNumber":"X","debtForInvoicesDueDateNotPassed":0.0,"isTouz":false,"smartMeter":false,"producerType":1,"isDomestic":true}],"contractAmount":2,"totalToPay":0.0},"reponseDescriptor":{"isSuccess":true,"code":"0","description":""}}
2024-12-05 19:28:43.218 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/content/en-US/calculators/gadget
2024-12-05 19:28:43.497 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <200>: {"gadget_Calculator_Rates":{"lastUpdated":"2024-02-01T00:00:00Z","homeRate":0.5252,"generalRate":0.5252,"vat":17.0},"gadget_Calculator_Actions":{"additionalInfo":[{"displaySettings":[],"link":"/en/email-invoice/","icon":"https://ieccontent.iec.co.il//media/bnwhvv1d/mail_v2.svg","description":"Receipt of invoice by email"}]},"electric_Devices":[{"name":"Washing machine","calculationResolution":1,"powerUnit":4,"power":1.5,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Small refrigerator","calculationResolution":1,"powerUnit":3,"power":40.0,"avarageDurationTimeOfOperationInMinutes":1440.0},{"name":"Large refrigerator","calculationResolution":1,"powerUnit":3,"power":80.0,"avarageDurationTimeOfOperationInMinutes":1440.0},{"name":"Electric water heater (\"boiler\")","calculationResolution":1,"powerUnit":4,"power":2.5,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Cooking, grilling and baking oven","calculationResolution":1,"powerUnit":4,"power":2.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Electric stove top","calculationResolution":2,"powerUnit":4,"power":6.0,"avarageDurationTimeOfOperationInMinutes":50.0},{"name":"Shabbat hot plate","calculationResolution":1,"powerUnit":3,"power":400.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Electric heater","calculationResolution":1,"powerUnit":4,"power":2.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Air-conditioner","calculationResolution":1,"powerUnit":2,"power":2.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Tumble dryer","calculationResolution":1,"powerUnit":4,"power":3.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Dishwasher for 6-8 sets of dishes","calculationResolution":1,"powerUnit":4,"power":1.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Dishwasher for 12-14 sets of dishes","calculationResolution":1,"powerUnit":4,"power":1.5,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Dishwasher","calculationResolution":1,"powerUnit":4,"power":1.5,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Incandescent lamp","calculationResolution":1,"powerUnit":3,"power":100.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"\"Regular\" fluorescent lamp","calculationResolution":1,"powerUnit":3,"power":300.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"\"Regular\" halogen lamp","calculationResolution":1,"powerUnit":3,"power":200.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"LED lamp","calculationResolution":1,"powerUnit":3,"power":15.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Microwave oven","calculationResolution":2,"powerUnit":4,"power":1.5,"avarageDurationTimeOfOperationInMinutes":2.0},{"name":"Electric kettle","calculationResolution":2,"powerUnit":4,"power":2.2,"avarageDurationTimeOfOperationInMinutes":3.0},{"name":"Vacuum cleaner","calculationResolution":2,"powerUnit":4,"power":1.0,"avarageDurationTimeOfOperationInMinutes":10.0},{"name":"Iron","calculationResolution":2,"powerUnit":4,"power":2.0,"avarageDurationTimeOfOperationInMinutes":45.0},{"name":"Food processor","calculationResolution":2,"powerUnit":4,"power":0.5,"avarageDurationTimeOfOperationInMinutes":15.0},{"name":"Toaster oven","calculationResolution":2,"powerUnit":4,"power":1.2,"avarageDurationTimeOfOperationInMinutes":15.0},{"name":"Television set","calculationResolution":1,"powerUnit":3,"power":200.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Hair dryer","calculationResolution":2,"powerUnit":4,"power":1.0,"avarageDurationTimeOfOperationInMinutes":10.0},{"name":"Electric blanket","calculationResolution":1,"powerUnit":3,"power":100.0,"avarageDurationTimeOfOperationInMinutes":60.0},{"name":"Personal computer","calculationResolution":1,"powerUnit":3,"power":120.0,"avarageDurationTimeOfOperationInMinutes":60.0}],"title":"Calculators BY Device","seoModel":{"title":"","additionalInfo":[]},"unavailable_Service_Alerts":[]}
2024-12-05 19:28:43.502 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il/api/content/en-US/content/tariffs/contentpages/homeelectricitytariff
2024-12-05 19:28:43.517 DEBUG (MainThread) [iec_api.commons] HTTP GET Response <204>: 
2024-12-05 19:28:43.517 WARNING (MainThread) [iec_api.commons] Failed call: (Code 204): No Content
2024-12-05 19:28:43.518 ERROR (MainThread) [custom_components.iec.coordinator] Failed updating data. Exception: object of type 'NoneType' has no len()
2024-12-05 19:28:43.527 ERROR (MainThread) [custom_components.iec.coordinator] Traceback (most recent call last):
  File "/config/custom_components/iec/coordinator.py", line 647, in _async_update_data
  File "/config/custom_components/iec/coordinator.py", line 385, in _update_data
  File "/config/custom_components/iec/coordinator.py", line 191, in _get_kva_tariff
  File "/config/deps/lib/python3.12/site-packages/iec_api/iec_client.py", line 511, in get_kva_tariff
  File "/config/deps/lib/python3.12/site-packages/iec_api/static_data.py", line 93, in get_kva_tariff
  File "/config/deps/lib/python3.12/site-packages/iec_api/static_data.py", line 42, in _get_tariffs
  File "/config/deps/lib/python3.12/site-packages/iec_api/commons.py", line 125, in send_get_request
  File "/config/deps/lib/python3.12/site-packages/iec_api/commons.py", line 92, in parse_error_response
2024-12-05 19:28:43.528 DEBUG (MainThread) [custom_components.iec.coordinator] Finished fetching Iec data in 3.230 seconds (success: False)
2024-12-05 19:28:43.528 ERROR (MainThread) [custom_components.iec] Failed to fetch initial data: Failed Updating IEC data
2024-12-05 19:28:43.563 INFO (MainThread) [homeassistant.components.sensor] Setting up iec.sensor
2024-12-05 19:28:43.564 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up iec platform for sensor
  File "/config/custom_components/iec/sensor.py", line 335, in async_setup_entry
2024-12-05 19:28:43.567 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up iec.binary_sensor
2024-12-05 19:28:43.567 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up iec platform for binary_sensor
  File "/config/custom_components/iec/binary_sensor.py", line 70, in async_setup_entry
```

**Comment by GuyKh** [comment]
It's related to IEC change in KVA calculation. Try again sometime laterr
