### ISSUE TITLE
Support multiple contracts/meters

### ISSUE THREAD

**Issue by GuyKh** [GuyKh/iec-custom-component#51]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

What to do when I have two meters or contracts etc.

### Describe the solution you'd like

Select which contract to use on the integration config-flow.

### Describe alternatives you've considered

Importing all (active) meters together

### Additional context

.

**Comment by GuyKh** [comment]
@eleibzon - I see it's a relevant scenario, and still is not supported.
Can you check if you have 2 meters under the same **contract** or **two contracts with a single meter in each** ?

**Comment by eleibzon** [comment]
its 2 different contracts

**Comment by GuyKh** [comment]
@eleibzon - added a new pre-release (0.0.20) - can you try to install it?
It should support multiple contracts

**Comment by eleibzon** [comment]
New problem! Can add an account at all
![IMG_9735](https://github.com/GuyKh/iec-custom-component/assets/155832972/055b80d4-043e-4628-8a4a-a5b660e76a4f)

**Comment by GuyKh** [comment]
Can you send me the error from the logs?

**Comment by eleibzon** [comment]
```
2024-03-12 08:54:03.785 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 197, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 405, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 546, in _async_handle_step
    self._raise_if_step_does_not_exist(flow, result["step_id"])
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 569, in _raise_if_step_does_not_exist
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler ConfigEntriesFlowManager doesn't support step select_contracts
```

**Comment by GuyKh** [comment]
@eleibzon Let's try again with beta [0.0.20b1](https://github.com/GuyKh/iec-custom-component/releases/tag/0.0.20b1)

**Comment by GuyKh** [comment]
I need to fix something with the translation there I think too

**Comment by eleibzon** [comment]
![Untitled](https://github.com/GuyKh/iec-custom-component/assets/155832972/e4646321-718f-4078-a9e0-e905aba514b9)

**Comment by GuyKh** [comment]
@eleibzon let's try with `0.0.20b2`

**Comment by eleibzon** [comment]
![Untitled](https://github.com/GuyKh/iec-custom-component/assets/155832972/b98b2b5e-f12d-449e-919c-80ae7268c1ea)

**Comment by eleibzon** [comment]
![Untitled](https://github.com/GuyKh/iec-custom-component/assets/155832972/380aad1e-ab0d-4d66-bb6d-89b955f7a163)

**Comment by GuyKh** [comment]
God damn. Little mistake. in 5 mins you'll have 0.0.20b3

**Comment by eleibzon** [comment]
```
2024-03-12 14:56:04.417 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: 'NoneType' object has no attribute 'smart_meter'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 144, in _async_update_data
    await self._insert_statistics(contract_id, contracts.get(contract_id).smart_meter)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'smart_meter'
2024-03-12 14:56:11.296 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: 'NoneType' object has no attribute 'smart_meter'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 144, in _async_update_data
    await self._insert_statistics(contract_id, contracts.get(contract_id).smart_meter)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'smart_meter'
2024-03-12 14:56:23.233 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: 'NoneType' object has no attribute 'smart_meter'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 144, in _async_update_data
    await self._insert_statistics(contract_id, contracts.get(contract_id).smart_meter)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'smart_meter'
```

**Comment by GuyKh** [comment]
Let's try again with 0.0.20b4

**Comment by eleibzon** [comment]
Works perfectly! Thank you.

**Comment by GuyKh** [comment]
Awesome! 
Thanks for testing these things out! :)

**Comment by ohadbenita** [comment]
Does this relate to cases where I use Cellcom as my provider and get the below error?

```
2024-03-12 17:43:52.745 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: Field "data" of type GetInvoicesBody in ResponseWithDescriptor has invalid value None
```

**Comment by GuyKh** [comment]
@ohadbenita I need some extra debug logs for that

**Comment by ohadbenita** [comment]
> @ohadbenita I need some extra debug logs for that

Sure, here you go:

```
2024-03-12 17:43:52.745 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: Field "data" of type GetInvoicesBody in ResponseWithDescriptor has invalid value None
Traceback (most recent call last):
  File "<string>", line 7, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
  File "<string>", line 19, in __mashumaro_from_dict__
ValueError: Argument for iec_api.models.invoice.GetInvoicesBody.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 149, in _async_update_data
    billing_invoices = await self.api.get_billing_invoices(self._bp_number, contract_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 324, in get_billing_invoices
    return await data.get_billing_invoices(self._session, self._token, bp_number, contract_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 181, in get_billing_invoices
    return await _get_response_with_descriptor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 64, in _get_response_with_descriptor
    response_with_descriptor = decoder.decode(response)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 9, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
mashumaro.exceptions.InvalidFieldValue: Field "data" of type GetInvoicesBody in ResponseWithDescriptor has invalid value None
```

**Comment by GuyKh** [comment]
That's a very strange behavior when a call to GetInvoices returns `null`.

Can you try to log on to IEC website and take a look at your Invoices there to see what happens?

**Comment by GuyKh** [comment]
@ohadbenita - can you open a new issue with this log?

**Comment by ohadbenita** [comment]
> @ohadbenita - can you open a new issue with this log?

Sure, see #67
