### ISSUE TITLE
No invoices found error - Initialization fails

### ISSUE THREAD

**Issue by ohadbenita** [GuyKh/iec-custom-component#67]
## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4829
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 26, 2024 at 03:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-3.ui.nabu.casa
certificate_status | ready
instance_id | d7bb6698d43840488fca42c7de381b58
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 18
views | 4
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 13, 2024 at 11:56
-- | --
current_recorder_run | March 12, 2024 at 17:28
estimated_db_size | 4021.73 MiB
database_engine | mysql
database_version | 10.6.11

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Component initialization fails

### Reproduction steps

1. Login to the IEC component using the OTP code for a user that is paying through Cellcom or another provider that's not IEC.
2. The issue should be reproduced due to the fact that IEC doesn't issue any invoices to these users.

### Debug logs

```text
2024-03-12 17:43:52.745 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: Field "data" of type GetInvoicesBody in ResponseWithDescriptor has invalid value None
Traceback (most recent call last):
  File "<string>", line 7, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
  File "<string>", line 19, in __mashumaro_from_dict__
ValueError: Argument for iec_api.models.invoice.GetInvoicesBody.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 149, in _async_update_data
    billing_invoices = await self.api.get_billing_invoices(self._bp_number, contract_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 324, in get_billing_invoices
    return await data.get_billing_invoices(self._session, self._token, bp_number, contract_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 181, in get_billing_invoices
    return await _get_response_with_descriptor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ie
```

**Comment by GuyKh** [comment]
Just to make sure, IEC website works for your, right?
What happens when you try to see your Invoices from there?

**Comment by enudler** [comment]
i have same issues, iec site works for me but i dont have invoices yet (moved a month ago)

**Comment by GuyKh** [comment]
Got it. I'll try to fix it soon

**Comment by GuyKh** [comment]
@enudler @ohadbenita 
Can you try with **BETA** version `0.0.21b1` (https://github.com/GuyKh/iec-custom-component/releases/tag/0.0.21b1)

**Comment by enudler** [comment]
for sure, will check it later today when i get home

**Comment by enudler** [comment]
I just checked and i got my first invoice yesterday so evetythins works fine for me at 0.0.2

**Comment by GuyKh** [comment]
Should be ok with version `0.0.21`

**Comment by ohadbenita** [comment]
> Should be ok with version `0.0.21`

Still fails with 0.0.21:

```
2024-03-15 16:58:54.936 DEBUG (MainThread) [custom_components.iec.coordinator] Checking if API token needs to be refreshed
2024-03-15 16:58:56.971 DEBUG (MainThread) [custom_components.iec.coordinator] All Contract Ids: [xxxx, yyyy]
2024-03-15 16:58:56.971 DEBUG (MainThread) [custom_components.iec.coordinator] Processing xxxx
2024-03-15 16:58:56.971 DEBUG (MainThread) [custom_components.iec.coordinator] Updating statistics for IEC Contract 348265224
2024-03-15 16:58:59.609 DEBUG (MainThread) [custom_components.iec.coordinator] Last statistics are from 2024-03-14 14:00:00
2024-03-15 16:58:59.609 DEBUG (MainThread) [custom_components.iec.coordinator] Calculated from_date = 2024-03-14 14:00:00
2024-03-15 16:58:59.609 DEBUG (MainThread) [custom_components.iec.coordinator] Fetching consumption from 2024-03-14 14:00:00
2024-03-15 16:59:01.925 DEBUG (MainThread) [custom_components.iec.coordinator] Last Consumption Sum for 348265224: 282.1149999999996
2024-03-15 16:59:01.925 DEBUG (MainThread) [custom_components.iec.coordinator] Last Estimated Cost Sum for 348265224: 173.3596675000002
2024-03-15 16:59:01.929 DEBUG (MainThread) [custom_components.iec.coordinator] Last hour fetched for xxxx: 2024-03-14 14:00:00+02:00
2024-03-15 16:59:01.929 DEBUG (MainThread) [custom_components.iec.coordinator] New Consumption Sum for 348265224: 282.1149999999996
2024-03-15 16:59:01.930 DEBUG (MainThread) [custom_components.iec.coordinator] New Estimated Cost Sum for 348265224: 173.3596675000002
2024-03-15 16:59:04.792 ERROR (MainThread) [custom_components.iec.coordinator] Unexpected error fetching Iec data: Field "data" of type GetInvoicesBody in ResponseWithDescriptor has invalid value None
Traceback (most recent call last):
  File "<string>", line 7, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
  File "<string>", line 19, in __mashumaro_from_dict__
ValueError: Argument for iec_api.models.invoice.GetInvoicesBody.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 149, in _async_update_data
    billing_invoices = await self.api.get_billing_invoices(self._bp_number, contract_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 324, in get_billing_invoices
    return await data.get_billing_invoices(self._session, self._token, bp_number, contract_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 181, in get_billing_invoices
    return await _get_response_with_descriptor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/data.py", line 64, in _get_response_with_descriptor
    response_with_descriptor = decoder.decode(response)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 9, in __mashumaro_from_dict_1d2cb13ddbf239913f0f50f5018a33ba__
mashumaro.exceptions.InvalidFieldValue: Field "data" of type GetInvoicesBody in ResponseWithDescriptor has invalid value None

```

**Comment by GuyKh** [comment]
Can you also add `iec_api: debug` to loggers and fetch the logs for the call to `https://iecapi.iec.co.il//api/billingCollection/invoices`

I'm trying to decode this:
```
    s = '{"data": null,"reponseDescriptor": {"isSuccess": true,"code": null,"description": null}}'
    d = json.loads(s)
    invoices = invoice_decoder.decode(d)
```

And it works like a charm, so I wonder how does the response looks like.

**Comment by GuyKh** [comment]
It is related but very odd. Are you sure that the `ContractId` (you can see it in the sensor attributes and debug logs) is correct?

Just to be sure, you're seeing logs like this:
```
2024-03-19 03:40:24.690 DEBUG (MainThread) [iec_api.iec_client] Tariff is missing or expired, fetching kwh tariff from IEC API
2024-03-19 03:40:24.690 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/content/en-US/content/tariffs/contentpages/homeelectricitytariff
```

(note the `iec_api`)

**Comment by ohadbenita** [comment]
> ContractId

It seems correct but I have two contracts under my name, one of which don't have an invoice yet. I'll double-check a bit later and get back to you about this.

**Comment by GuyKh** [comment]
I see. 
Interesting, I'd love to see the API call JSON response from the logs if possible

**Comment by GuyKh** [comment]
Merged a fix, let's try the next version?

**Comment by ohadbenita** [comment]
> I see. Interesting, I'd love to see the API call JSON response from the logs if possible

Sorry, for the late response, here you go:

```
2024-03-18 21:24:50.647 DEBUG (MainThread) [iec_api.commons] HTTP GET: https://iecapi.iec.co.il//api/billingCollection/invoices/348265224/0200153747
2024-03-18 21:24:52.155 DEBUG (MainThread) [iec_api.commons] HTTP GET Response: {'data': None, 'reponseDescriptor': {'isSuccess': False, 'code': '02', 'description': 'לא קיימים תשלומים או חובות לחוזה'}}
```

**Comment by GuyKh** [comment]
Great. Supposed to be working

**Comment by ohadbenita** [comment]
Confirmed to be working with 0.0.22, highly appreciated @GuyKh
